##
##
## Introduction
## ============
##
## Makefile for iqist/src/tools/hibiscus directory.
##
## Usage
## =====
##
## 'make' or 'make clean'
##
## Author
## ======
##
## This building system is designed, created, implemented, and maintained by
##
## Li Huang // email: huangli712@gmail.com
##
## History
## =======
##
## 09/30/2014 by li huang
##
##

default: all

all: build-entropy1 build-entropy2 build-sac build-script build-swing build-toolbox
clean: clean-entropy1 clean-entropy2 clean-sac clean-script clean-swing clean-toolbox

# targets for entropy1
build-entropy1:
	cd ./entropy1; pwd; make

clean-entropy1:
	cd ./entropy1; pwd; make clean

# targets for entropy2
build-entropy2:
clean-entropy2:

# targets for sac
build-sac:
clean-sac:

# targets for script
build-script:
clean-script:

# targets for swing
build-swing:
clean-swing:

# targets for toolbox
build-toolbox:
clean-toolbox:
