##
##
## Introduction
## ============
##
## Makefile for iqist/src/tools/hibiscus directory.
##
## Usage
## =====
##
## 'make' or 'make clean'
##
## Author
## ======
##
## This building system is designed, created, implemented, and maintained by
##
## Li Huang // email: lihuang.dmft@gmail.com
##
## History
## =======
##
## 11/03/2014 by li huang (created)
## 04/06/2017 by li huang (last modified)
##
##

default: all

all:

clean:
	rm -fr *.o
	rm -fr *.pyc
	rm -fr *.so

clean-dat:
	rm -fr *.dat
	rm -fr *.out
	rm -fr *.data

clean-all: clean clean-dat
