##
##
## Introduction
## ============
##
## Makefile for iqist/src/tools directory.
##
## Usage
## =====
##
## 'make', 'make clean', 'make clean-dat' or 'make clean-all'
##
## Author
## ======
##
## This building system is designed, created, and maintained by
##
## Li Huang // email: lihuang.dmft@gmail.com
##
## History
## =======
##
## 11/03/2014 by li huang (created)
## 04/15/2019 by li huang (last modified)
##
##

default: all

all:

clean:
	rm -f *.pyc

clean-dat:
	rm -f *.dat
	rm -f *.out

clean-all: clean clean-dat
